authors/urls.py
from django.conf.urls import url

from .views import AuthorCreateView, AuthorListView

urlpatterns = [
    url(r'^$', AuthorListView.as_view(), name='list',),
    url(r'^create/$', AuthorCreateView.as_view(), name='create',),
]

books/urls.py
from django.conf.urls import url

from .views import BookCreateView, BookDetailView, BookListView, BookUpdateView

urlpatterns = [
    url(r'^$', BookListView.as_view(), name='list',),
    url(r'^create/$', BookCreateView.as_view(), name='create',),
    url(r'^detail/(?P<slug>.*)/$', BookDetailView.as_view(), name='detail',),
    url(r'^update/(?P<slug>.*)/$', BookUpdateView.as_view(), name='update',),
]

translate-adventure/urls.py
from __future__ import absolute_import, unicode_literals
from django.conf.urls import include, url
from django.contrib import admin

from books import urls as books_urls
from authors import urls as authors_urls


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^books/', include(books_urls, namespace='books')),
    url(r'^authors/', include(authors_urls, namespace='authors')),
]

authors/models.py
from django.db import models
from django.utils.text import slugify
from django.utils.translation import ugettext_lazy as _


class Author(models.Model):
    first_name = models.CharField(blank=True, max_length=100)
    last_name = models.CharField(blank=True, max_length=100)
    birth_day = models.DateField()
    biography = models.CharField(blank=True, max_length=100)

    class Meta:
        verbose_name = _('Author')
        verbose_name_plural = _('Authors')

    def __unicode__(self):
        return '%s %s' % (self.first_name, self.last_name)

    def save(self, *args, **kwargs):
        full_name = '%s %s' % (self.first_name, self.last_name)
        self.slug = slugify(full_name)
        super(Author, self).save(*args, **kwargs)

books/models.py
from django.db import models
from django.utils.text import slugify
from django.utils.translation import ugettext_lazy as _

from authors.models import Author

CATEGORY = (
    ('maths', _('Maths')),
    ('science', _('Science')),
    ('biology', _('Biology')),
    ('geography', _('Geography')),
)


class Book(models.Model):
    name = models.CharField(blank=True, max_length=100)
    category = models.CharField(blank=True, max_length=100, choices=CATEGORY)
    description = models.CharField(blank=True, max_length=100)
    author = models.ForeignKey(Author)
    slug = models.SlugField(unique=True, blank=True)

    class Meta:
        verbose_name = _('Book')
        verbose_name_plural = _('Books')

    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Book, self).save(*args, **kwargs)

preferences/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _


AVAILABLE_LANGUAGES = (
    ('en', _('English')),
    ('es', _('Spanish')),
)


class Preference(models.Model):
    user = models.OneToOneField(User)
    language = models.CharField(blank=True, max_length=100, choices=AVAILABLE_LANGUAGES, default='en')

    class Meta:
        verbose_name = 'Preference'
        verbose_name_plural = 'Preferences'

    def __unicode__(self):
        return self.user.username

books/forms.py
from django import forms

from .models import Book


class BookForm(forms.ModelForm):

    class Meta:
        model = Book
        fields = ['name', 'category', 'author', 'description']
        widgets = {
            'description': forms.Textarea(attrs={'cols': 20, 'rows': 10, 'class': 'materialize-textarea'}),
        }

    def __init__(self, *args, **kwargs):
        super(BookForm, self).__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super(BookForm, self).clean()
        return cleaned_data

authors/views.py
from django.views.generic import CreateView, ListView

from.models import Author


class AuthorCreateView(CreateView):
    model = Author
    template_name = 'author-create.html'
    fields = ['first_name', 'last_name']
    success_url = 'authors:list'


class AuthorListView(ListView):
    context_object_name = 'authors'
    model = Author
    template_name = 'author-list.html'

books/views.py
from django.views.generic import CreateView, DetailView, ListView, UpdateView
from django.core.urlresolvers import reverse_lazy

from .models import Book
from .forms import BookForm


class BookCreateView(CreateView):
    model = Book
    form_class = BookForm
    template_name = 'book-create.html'
    success_url = reverse_lazy('books:list')


class BookDetailView(DetailView):
    model = Book
    slug_field = 'slug'
    slug_url_kwarg = 'slug'
    context_object_name = 'book'
    template_name = 'book-detail.html'


class BookListView(ListView):
    model = Book
    context_object_name = 'books'
    template_name = 'book-list.html'


class BookUpdateView(UpdateView):
    model = Book
    fields = ['name', 'category']
    success_url = reverse_lazy('books:list')
    template_name = 'book-update.html'

preferences/views.py
from django.shortcuts import render

# Create your views here.

authors/templates/author-create.html
{% extends "base.html" %}
{% load i18n %}
{% block title %} {% endblock title %}
{% block content %}
		<form action="." method="post" class="padding-top">
			{% csrf_token %}
			<div class="row">
				<div class="input-field col s6 offset-s3">
					<label for="id_fist_name">{% trans "First Name" %}</label>
					{{ form.first_name }}
				</div>
			</div>
			<div class="row">
				<div class="input-field col s6 offset-s3">
					<label for="id_last_name">{% trans "Last Name" %}</label>
					{{ form.last_name }}
				</div>
			</div>
			<div class="row">
				<div class="input-field col s6 offset-s3">
					<button class="btn waves-effect waves-light col s12" type="submit">
						{% trans "Submit" %}
					</button>
				</div>
			</div>
		</form>
{% endblock content %}

authors/templates/author-list.html
{% extends "base.html" %}
{% load i18n %}
{% block title %} {% trans "Book list" %} {% endblock title %}
{% block content %}
	<div class="row padding-top">
		<div class="col s8 offset-s2">
			<table class="centered striped">
				<thead>
					<tr>
							<th data-field="name">{% trans "Name" %}</th>
					</tr>
				</thead>
				<tbody>
					{% for author in authors %}
						<tr>
							<td>{{ author.first_name }}  {{ author.last_name }}</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
	<div class="row padding-top">
		<a class="btn waves-effect waves-light col s8 offset-s2 " href="{% url 'authors:create' %}">+</a>
	</div>
{% endblock content %}

books/templates/base.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
		<title>{% block title %}{% endblock title %}</title>
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.0/css/materialize.min.css">
	</head>
	<body>
		{% block content %}{% endblock content %}
	</body>
	<script src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.0/js/materialize.min.js"></script>
	{% block js %}{% endblock js %}
</html>

books/templates/book-create.html
{% extends "book-form.html" %}
{% load i18n %}
{% block title %} {% trans "Add a book" %} {% endblock title %}
{% block form_title %} {% trans "Create a new book" %} {% endblock form_title %}

books/templates/book-detail.html
{% extends "base.html" %}
{% load i18n %}
{% block title %} Book - {{ book.name }} {% endblock title %}
{% block content %}
	<div class="row padding-top">
		<div class="col s12 m6">
			<div class="card medium blue-grey darken-1">
				<div class="card-content white-text">
					<span class="card-title">{{ book.name }} - {{ book.author }}</span>
					<p>
						{{ book.description }}
					</p>
				</div>
				<div class="card-action">
					<a href="{% url 'books:update' book.slug %}">{% trans "Update" %}</a>
					{# <a href="{% url 'books:delete' book.slug %}">{% trans "Delete" %}</a> #}
				</div>
			</div>
		</div>
	</div>
{% endblock content %}

books/templates/book-form.html
{% extends "base.html" %}
{% load i18n %}
{% block title %} {% endblock title %}
{% block content %}
	<div class="container">
		<div class="row">
			<div class="col s8 offset-s2">
				<h1 class="center-align">{% block form_title %}{% endblock form_title %}</h1>
			</div>
		</div>
		<form action="." method="post">
			{% csrf_token %}
			<div class="row">
				<div class="input-field col s6 offset-s3">
					<label for="id_name">{% trans "Name" %}</label>
					{{ form.name }}
				</div>
			</div>
			<div class="row">
				<div class="input-field col s6 offset-s3">
					{{ form.category }}
				</div>
			</div>
			<div class="row">
				<div class="input-field col s6 offset-s3">
					<button class="btn waves-effect waves-light col s12" type="submit">
						{% trans "Submit" %}
					</button>
				</div>
			</div>
		</form>
	</div>
{% endblock content %}
{% block js %}
	<script type="text/javascript">
		$(document).ready(function() {
			$('select').material_select();
		});
	</script>
{% endblock js %}

books/templates/book-list.html
{% extends "base.html" %}
{% load i18n %}
{% block title %} {% trans "Book list" %} {% endblock title %}
{% block content %}
	<div class="container">
		<div class="row">
			<div class="col s8 offset-s2">
				<h1 class="center-align">{% trans "Book list" %}</h1>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col s8 offset-s2">
			<table class="centered striped">
				<thead>
					<tr>
							<th data-field="name">{% trans "Name" %}</th>
							<th data-field="category">{% trans "Category" %}</th>
					</tr>
				</thead>
				<tbody>
					{% for book in books %}
						<tr>
							<td>{{ book.name }}</td>
							<td>{{ book.category }}</td>
						</tr>
					{% empty %}

					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
{% endblock content %}

books/templates/book-update.html
{% extends "book-form.html" %}
{% load i18n %}
{% block title %} Update {{ book.slug }} {% endblock title %}
{% block form_title %}
	{% blocktrans with book.slug as book_name %}
		Update {{ book_name }} book
	{% endblocktrans %}
{% endblock form_title %}

translate-adventure/templates/base.html
<!DOCTYPE html>
{% load static from staticfiles %}
{% load i18n %}
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
  <title>{% block title %}{% endblock title %}</title>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.0/css/materialize.min.css" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="{% static "css/style.css" %}" type="text/css" rel="stylesheet" media="screen,projection"/>
</head>
<body>
  <nav class="light-green lighten-1" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="#" class="brand-logo">{% trans "Book Manager" %}</a>
      <ul class="right hide-on-med-and-down">
        <li><a href="{% url 'books:list' %}">{% trans "Books" %}</a></li>
        <li><a href="{% url 'authors:list' %}">{% trans "Authors" %}</a></li>
      </ul>
      <ul id="nav-mobile" class="side-nav">
          <li><a href="{% url 'books:list' %}">{% trans "Books" %}</a></li>
          <li><a href="{% url 'authors:list' %}">{% trans "Authors" %}</a></li>
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
  </nav>
  <div class="container">
    {% block content %}{% endblock content %}
  </div>
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="{% static "js/init.js" %}"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.0/js/materialize.min.js"></script>
  {% block js %}{% endblock js %}
  </body>
</html>